version: '3.8'
services:
  app:
    build: .
    networks:
      - BiNetwork
    ports:
      - "8050:8050"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bi_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - BiNetwork
    ports:
      - "3306:3306"

networks:
  BiNetwork:
    driver: bridge
