version: '3.8'
services:
  app:
    build: .
    networks:
      - BiNetwork
    ports:
      - "8050:8050"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - BiNetwork
    ports:
      - "3306:3306"

networks:
  BiNetwork:
    driver: bridge
