executor: parallel
tasks:
  - source: ./Extract/Input/extract_coffee_distribution.py
    name: extract_coffee_distribution
    product:
      nb: ./Extract/Output/extract_coffee_distribution.ipynb
    params:
      data_path: '{{data_path}}'
  - source: ./Extract/Input/extract_coffee_quality_data_cqi.py
    name: extract_coffee_quality_data_cqi
    product:
      nb: ./Extract/Output/extract_coffee_quality_data_cqi.ipynb
    params:
      data_path: '{{data_path}}'
  - source: ./Extract/Input/extract_coffee_reviews_dataset.py
    name: extract_coffee_reviews_dataset
    product:
      nb: ./Extract/Output/extract_coffee_reviews_dataset.ipynb
    params:
      data_path: '{{data_path}}'
  - source: ./Extract/Input/extract_coffee_sales.py
    name: extract_coffee_sales
    product:
      nb: ./Extract/Output/extract_coffee_sales.ipynb
    params:
      data_path: '{{data_path}}'
  - source: ./Extract/Input/extract_coffee_shop_sales_dataset.py
    name: extract_coffee_shop_sales_dataset
    product:
      nb: ./Extract/Output/extract_coffee_shop_sales_dataset.ipynb
    params:
      data_path: '{{data_path}}'
