executor: parallel
tasks:
  - source: ./Extract/Input/extract.py
    name: extract
    product:
      nb: ./Extract/Output/extract.ipynb
      data1: '{{extract_path}}/distribution/psd_coffee.csv'
      data2: '{{extract_path}}/distribution/psd_coffee.xls'
      data3: '{{extract_path}}/quality/df_arabica_clean.csv'
      data4: '{{extract_path}}/reviews/coffee_analysis.csv'
      data5: '{{extract_path}}/reviews/simplified_coffee.csv'
      data6: '{{extract_path}}/sales/index.csv'
      data7: '{{extract_path}}/shop-sales/Coffee Shop Sales.xlsx'
    params:
      extract_path: '{{extract_path}}'
  - source: ./Transform/Input/clean_distribution.py
    name: clean_distribution
    product:
      nb: ./Transform/Output/clean_distribution.ipynb
      data: '{{transform_path}}/clean_distribution.csv'
    params:
      extract_path: '{{extract_path}}'
      transform_path: '{{transform_path}}'
